Shvb publish remind
spacesvr/muse-universe pull request #67
Opened 2021-08-24 03:10 UTC by veltsonbastien

2021-08-24 03:34 UTC, ianyimi requested changes

2021-08-24 03:34 UTC, ianyimi commented on src/realities/BuilderReality/tools/BuilderWand/index.tsx
> +import world from "../../../../layers/simulation"
"layers/simulation" should work

2021-08-24 03:34 UTC, ianyimi commented on src/realities/BuilderReality/tools/BuilderWand/index.tsx
> +  },[history.hasPrev])
remove this part if it doesnt work

2021-08-24 03:34 UTC, ianyimi commented on src/realities/BuilderReality/tools/BuilderWand/index.tsx
> +          }
itd be better to move all the logic from this file to another file called PublishReminder.tsx and have that file return this chunk of code, then you can import that file and call it here as <PublishReminder />

2021-08-24 03:34 UTC, ianyimi commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
you can remove all of the .idea files from your prs. honestly im not sure what they are but they dont do anything functionally, just clutter the repo

2021-08-24 04:47 UTC, veltsonbastien commented on src/realities/BuilderReality/tools/BuilderWand/index.tsx
> +import world from "../../../../layers/simulation"
It doesn't work, I could just remove it if need be since I'm not using it yet

2021-08-24 04:49 UTC, veltsonbastien commented on src/realities/BuilderReality/tools/BuilderWand/index.tsx
> +  },[history.hasPrev])
👍

2021-08-24 10:14 UTC, ianyimi requested changes

2021-08-24 10:14 UTC, ianyimi commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
remove all .idea files

2021-08-24 10:14 UTC, ianyimi commented on src/realities/BuilderReality/tools/BuilderWand/index.tsx
> +
remove extra space

2021-08-24 10:14 UTC, ianyimi commented on src/realities/BuilderReality/tools/BuilderWand/index.tsx
> +          <PublishReminder />
remove extra space

2021-08-24 10:14 UTC, ianyimi commented on src/realities/BuilderReality/tools/BuilderWand/index.tsx
> +
remove extra space

2021-08-24 23:48 UTC, veltsonbastien commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
👍

2021-08-24 23:49 UTC, veltsonbastien commented on src/realities/BuilderReality/tools/BuilderWand/index.tsx
> +
👍

2021-08-24 23:49 UTC, veltsonbastien commented on src/realities/BuilderReality/tools/BuilderWand/index.tsx
> +          <PublishReminder />
which extra space?

2021-08-24 23:50 UTC, veltsonbastien commented on src/realities/BuilderReality/tools/BuilderWand/index.tsx
> +
👍

2021-08-24 23:50 UTC, veltsonbastien commented on src/realities/BuilderReality/tools/BuilderWand/index.tsx
> +          <PublishReminder />
I'm assuming you mean in PublishReminder and the closing tag, in that case -> 👍

2021-08-25 00:31 UTC, ianyimi requested changes

2021-08-25 00:31 UTC, ianyimi commented on src/realities/BuilderReality/tools/BuilderWand/index.tsx
> +import { RoundedBox, Text } from "@react-three/drei";
dont need text import anymore

2021-08-30 08:42 UTC, alex-shortt requested changes
PublishReminder should be under `.../tools/BuilderWand/components`

2021-08-30 08:42 UTC, alex-shortt commented on src/realities/BuilderReality/tools/PublishReminder/index.tsx
> +    },[])
did you get this working? this dependency array being empty would mean that this would never re-run, meaning that `history.hasPrev` would have to be true on the first iteration or else this would never run.

you should probably add `history` or `history.addPrev` to the dep array

2021-08-30 08:42 UTC, alex-shortt commented on src/realities/BuilderReality/tools/PublishReminder/index.tsx
> +    }, [remind]);
two intervals running at different points seems like it will be hard to be in sync, and it's a bit confusing to look at. would recommend:

```
 useEffect(() => {
        if(remind) return;

        setTimeout(() => {
            setRemind(true)
            setTimeout(() => setRemind(false), 1000 * 3)
        }, 1000 * 60 * 5);
    }, [remind]);
```

2021-08-30 18:42 UTC, closed without merging

2021-08-30 19:04 UTC, veltsonbastien commented on src/realities/BuilderReality/tools/PublishReminder/index.tsx
> +    },[])
okay done 👍

2021-08-30 19:05 UTC, veltsonbastien commented on src/realities/BuilderReality/tools/PublishReminder/index.tsx
> +    }, [remind]);
okay, replaced 👍