Vb askfortelephone
spacesvr/muse-universe pull request #78
Opened 2021-09-10 19:21 UTC by veltsonbastien

All that's left should be the fixing up in the backend.

2021-09-13 21:29 UTC, alex-shortt requested changes
also on the backend side, i should run you through how to set up a local environment for it. i can do this one now, but let's find a time this week

2021-09-13 21:29 UTC, alex-shortt commented on src/layers/identity.tsx
> +      this.phone = json.phone;
don't see a reason to return the phone number from the backend user_info function

2021-09-13 21:29 UTC, alex-shortt commented on src/layers/identity.tsx
> +    this.phone = undefined;
don't see a reason to return the phone number from the backend user_info function

2021-09-13 21:29 UTC, alex-shortt commented on src/worlds/MuseHQ/dialogue/signup.ts
> +        { name: "cancel", nextKey: inKey },
would personally stray away from punctuation like that and keep it conversational. thinking..

"what's your phone number?"

but then add a skip option

{ name: "submit", nextKey: "signup-artist" },
{ name: "skip", nextKey: "signup-artist" }

2021-09-15 01:20 UTC, veltsonbastien commented on src/layers/identity.tsx
> +      this.phone = json.phone;
done 👍

2021-09-15 01:20 UTC, veltsonbastien commented on src/layers/identity.tsx
> +    this.phone = undefined;
done 👍

2021-09-15 01:45 UTC, veltsonbastien commented on src/worlds/MuseHQ/dialogue/signup.ts
> +        { name: "cancel", nextKey: inKey },
done 👍

2021-09-15 04:30 UTC, alex-shortt approved these changes

2021-09-15 04:30 UTC, merged