Buildertablecopy
spacesvr/muse-universe pull request #81
Opened 2021-09-13 19:32 UTC by benjaminha14

pls review :). 
Added button copy change at builder table, add popup when you visit your own website on mobile

2021-09-13 21:12 UTC, alex-shortt requested changes

2021-09-13 21:12 UTC, alex-shortt commented on package.json
> +    "react-device-detect": "^1.17.0",
don't need to add a package. to get mobile status you can use spacesvr, i'll show it below.

2021-09-13 21:12 UTC, alex-shortt commented on src/realities/BuilderReality/index.tsx
> +  const [stage, setStage] = useState(0);
the state seems to only be used inside the Mobile popup, so you can just create it in there instead of creating it here and passing it through props

2021-09-13 21:12 UTC, alex-shortt commented on src/realities/BuilderReality/index.tsx
>    }
1. remove comments 
2. for mobile state, i would use spacesvr

```
const { device } = useEnvironment()
if( device.mobile ) { ... }
```

3. i think more readable clauses would be 

```
if(!exists || !OWNS_WORLD) return <group>{children}</group>

if (device.mobile) {
  return <group>
    <MobilePopup />
    {children}
  </group>
}
```

2021-09-13 21:12 UTC, alex-shortt commented on src/realities/BuilderReality/index.tsx
> +
extra space

2021-09-13 21:12 UTC, alex-shortt commented on src/worlds/MuseHQ/components/WorldMenu/components/ConfigGenerator.tsx
> +      name: isMobile? "visit website": "go to builder",
to detect mobile i would use spacesvr

```
const { device } = useEnvironment()
if( device.mobile ) { ... }
```

2021-09-13 21:12 UTC, alex-shortt commented on src/realities/BuilderReality/components/MobilePopup/index.tsx
> +  const { stage, setStage } = props;
would definitely set up the state here rather than passing it in as a prop. also a more readable way to set up the state could look like the following

```
const [shown, setShown] = useState(false)

.
.

onClick: () => setShown(true)
```

2021-09-14 02:07 UTC, benjaminha14 commented on package.json
> +    "react-device-detect": "^1.17.0",
removed!

2021-09-14 02:07 UTC, benjaminha14 commented on src/realities/BuilderReality/index.tsx
> +  const [stage, setStage] = useState(0);
done got rid of it!

2021-09-14 02:07 UTC, benjaminha14 commented on src/realities/BuilderReality/index.tsx
>    }
removed comments and reformatted clauses

2021-09-14 02:32 UTC, alex-shortt approved these changes

2021-09-14 02:32 UTC, merged